version: '3.8'

services:
  hadoop-master:
    container_name: hadoop-master
    restart: on-failure
    build: .
    image: hadoop-master
    entrypoint: ['./entrypoint.sh', 'master']
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '9870:9870'
      - '7077:7077'
      - '8088:8088'

  hadoop-worker:
    image: hadoop-worker
    restart: on-failure
    build: .
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - hadoop-master
    env_file:
      - .env.spark
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps

  history-server:
    container_name: history-server
    restart: on-failure
    image: firegroup-spark
    build: .
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - hadoop-master
    env_file:
      - .env.spark
    ports:
      - '18080:18080'

  # kafka-0:
  #   image: docker.io/bitnami/kafka:3.5
  #   hostname: baolx.local
  #   restart: unless-stopped
  #   container_name: kafka-0
  #   ports:
  #     - '9092:9092'
  #     - '9093:9093'
  #   environment:
  #     KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  #     ALLOW_PLAINTEXT_LISTENER: "yes"
  #     KAFKA_HEAP_OPTS: "-Xms4G -Xmx8G"
  #     # KRaft settings
  #     KAFKA_CFG_NODE_ID: 0
  #     KAFKA_CFG_PROCESS_ROLES: "controller,broker"
  #     KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@baolx.local:9093"
  #     KAFKA_KRAFT_CLUSTER_ID: "ZWU5YmZhYjBhNGE5NDA2NW"
  #     KAFKA_CFG_BROKER_RACK: 1
  #     KAFKA_CFG_LOG_RETENTION_HOURS: 2
  #     KAFKA_CFG_NUM_PARTITIONS: 1
  #     # Listeners
  #     KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
  #     KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://baolx.local:9092"
  #     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  #     KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  #     KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

  # akhq:
  #   image: tchiotludo/akhq
  #   restart: unless-stopped
  #   depends_on:
  #     - kafka-0
  #   ports:
  #     - 8081:8080
  #   environment:
  #     AKHQ_CONFIGURATION: |
  #       akhq:
  #         connections:
  #           docker-kafka-server:
  #             properties:
  #               bootstrap.servers: "baolx.local:9092"
      
  # debezium:
  #   image: debezium/connect:2.4
  #   container_name: debezium
  #   restart: unless-stopped
  #   depends_on:
  #     - kafka-0
  #   ports:
  #     - 8083:8083
  #   environment:
  #     BOOTSTRAP_SERVERS: kafka-0:9092
  #     GROUP_ID: 1
  #     CONFIG_STORAGE_TOPIC: bao_connect_configs
  #     OFFSET_STORAGE_TOPIC: bao_connect_offsets
  #     STATUS_STORAGE_TOPIC: bao_connect_statuses
  #     HEAP_OPTS: -Xms4G -Xmx8G
  #     CONNECT_TOPIC_CREATION_ENABLE: 'true'
  #     CONNECT_CONFIG_PROVIDERS: file
  #     CONNECT_CONFIG_PROVIDERS_FILE_CLASS: org.apache.kafka.common.config.provider.FileConfigProvider
  #     CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
  #     CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
  #     CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
  #     CONNECT_PRODUCER_MAX_REQUEST_SIZE: 5048576
  #     CONNECT_CONSUMER_MAX_PARTITION_FETCH_BYTES: 5048576
  #     CONNECT_MAX_REQUEST_SIZE: 10485760
  #     OFFSET_FLUSH_TIMEOUT_MS: 60000  # default 5000
  #     OFFSET_FLUSH_INTERVAL_MS: 15000  # default 60000
  #     MAX_BATCH_SIZE: 32768  # default 2048
  #     MAX_QUEUE_SIZE: 131072  # default 8192
  #     MAX_REQUEST_SIZE: 10485760  # default 8192
  #     FETCH_MAX_BYTES: 5048576
  #     MAX_PARTITION_FETCH_BYTES: 5048576

  hbase-master:
    image: blueskyareahm/hbase-base:2.1.3
    command: master
    restart: on-failure
    ports:
      - 16000:16000
      - 16010:16010

  hbase-regionserver:
    image: blueskyareahm/hbase-base:2.1.3
    command: regionserver
    restart: on-failure
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301

  zookeeper:
    image: blueskyareahm/hbase-zookeeper:3.4.13
    restart: on-failure
    ports:
      - 2181:2181